### ISSUE TITLE
some error  at the end of the code 

### ISSUE THREAD

**Issue by Tempest6** [subpath/Keras_music_gereration#1]
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 8734 arrays: [array([[-0.61290323,  0.42222222]

it is laocation is about line 101  i have no idea how to fix it

#line 99 mid = MidiFile()
#line100 track = MidiTrack()
#line 101
#line 102 t = 0

**Comment by subpath** [comment]
Hi! Thanks for your feedback! Sorry, it did not run in the first attempt :(. I will try to look at this and fix it during the day. Cheers!

**Comment by Tempest6** [comment]
cheers!

**Comment by Tempest6** [comment]
cheers!

**Comment by subpath** [comment]
Hi! Sorry for delay! Could you please try again? 
There was an error, when I was passing list to fit method instead of numpy array
Let me know if it worked

**Comment by Tempest6** [comment]
it work thank you！
