### ISSUE TITLE
generated midis empty?

### ISSUE THREAD

**Issue by ak9250** [subpath/Keras_music_gereration#5]
I downloaded the midis generated here, Generated_song_epoch=10.mid but they were empty

**Comment by subpath** [comment]
Hi! There were two files in the repo, one of them was dummy empty file that I added accidentally during debugging, you probably talking about this file. Please check again. 
![image](https://user-images.githubusercontent.com/11722602/51081836-ae20ae80-170a-11e9-84e9-a65d2aba2268.png)

**Comment by ak9250** [comment]
Hi, I tried it again after you deleted the old one but the problem was it was not working in https://chrome.soundation.com/ which is what I was importing it into but when I tried it import into a simple midi player it works http://midiplayer.ehubsoft.net/. I generated a sample myself too using google colab but though it was empty, seems it only plays on some midi players?

**Comment by subpath** [comment]
Hm...I honestly don't know about that... On my laptop, it just opens in a Garage Band by default.

**Comment by ak9250** [comment]
ok I trained on the sample file you have provided and am getting this
![screen shot 2019-01-14 at 4 30 45 pm](https://user-images.githubusercontent.com/6818285/51142425-efec4a80-1819-11e9-8047-4036a4bee442.png)
![screen shot 2019-01-14 at 4 32 15 pm](https://user-images.githubusercontent.com/6818285/51142457-0abebf00-181a-11e9-9865-3c2e5fef915a.png)

**Comment by subpath** [comment]
It took me several years, but I finally updated the notebook : )
